"""Driver script — Step 3: run the FVS deployment simulation and render struts.

Loads the pickled :class:`VirtualStenting` case written by
:mod:`constructInitFD`, runs :meth:`~PyStenting.VirtualStenting.deploy`, and
optionally calls :meth:`~PyStenting.FlowDiverter.render_strut` to produce a
solid mesh.

Outputs written to ``<experiment_dir>/results/``:
  ``deployed_<pos>_stentEX<N>.stl``          — rendered solid stent (if render_param set)
  ``deployed_<pos>_stentEX<N>_norender.vtp`` — wireframe stent (if render_param empty)

NOTE: experiment number is currently derived from the Windows-style path string
``dir_path.split('\\')[1].split()[1]``.  This breaks on Linux.
Fix is tracked in REFACTOR_PLAN.md Phase 1.
"""

from __future__ import annotations

import argparse
import json
import pickle
import time

import PyStenting as ps
from Utils import *


def _parse_config(dir_path: str, pos: str) -> tuple[str, dict, dict, dict | bool]:
    """Load ``deployStent`` parameters for stent position *pos*.

    Args:
        dir_path: Experiment directory path.
        pos: Stent position — must be ``"inner"`` or ``"outer"``.

    Returns:
        ``(kind_FD, deploy_param, render_param, filter_param)``

    Raises:
        ValueError: If *pos* is not ``"inner"`` or ``"outer"``.
    """
    with open(dir_path + '/appSettings.json', 'r') as setting:
        if pos not in ("inner", "outer"):
            raise ValueError("stent position value must be either 'inner' or 'outer'")
        kind_FD = pos
        data = json.load(setting)["deployStent"][kind_FD]
        deploy_param = data["deploy_param"]
        render_param = data["render_param"]
        filter_param = data.get("filter", False)
        return kind_FD, deploy_param, render_param, filter_param


def loadFDCaseFile(filename: str) -> ps.VirtualStenting:
    """Deserialise a pickled :class:`~PyStenting.VirtualStenting` case from *filename*.

    Args:
        filename: Path to a ``.obj`` pickle file written by :mod:`constructInitFD`.

    Returns:
        Loaded :class:`~PyStenting.VirtualStenting` instance.

    Warning:
        Pickle files are Python-version and structure specific; load only files
        generated by the same codebase revision.
    """
    with open(filename, 'rb') as config_object_file:
        case: ps.VirtualStenting = pickle.load(config_object_file)
        return case


def main(dir_path: str, stent_pos: str) -> None:
    """Run the deployment simulation and write the result mesh.

    Args:
        dir_path: Experiment directory path.
        stent_pos: ``"inner"`` or ``"outer"``.
    """
    kind_FD, deploy_param, render_param, filter_param = _parse_config(dir_path, stent_pos)
    t1 = time.time()

    # TODO (Phase 1): replace Windows-only path parsing with pathlib.Path(dir_path).name
    experiment_number = dir_path.split('\\')[1].split()[1]

    case = loadFDCaseFile(
        '{}/results/init_{}_stentEX{}.obj'.format(dir_path, kind_FD, experiment_number)
    )
    result = case.deploy(
        tol=deploy_param["tol"],
        add_tol=deploy_param["add_tol"],
        step=deploy_param["step"],
        fstop=deploy_param["fstop"],
        max_iter=deploy_param["max_iter"],
        alpha=deploy_param["alpha"],
        verbose=deploy_param["verbose"],
        OC=deploy_param["OC"],
        render_gif=deploy_param.get("render_gif"),
        deployment_name=deploy_param.get("deployment_name"),
    )

    t2 = time.time()
    print('Deployment simulation done, dt_deploy=%.2f s' % (t2 - t1))

    if len(render_param) != 0:
        result = result.render_strut(
            n=render_param["n"],
            h=render_param["h"],
            threshold=render_param["threshold"],
        )
        if filter_param:
            result.subdivide(filter_param['nsub'], subfilter=filter_param['kind'])
        result.save("{}/results/deployed_{}_stentEX{}.stl".format(
            dir_path, kind_FD, experiment_number))
        t3 = time.time()
        print('Rendering done, dt_render=%.2f s' % (t3 - t2))
    else:
        result.save("{}/results/deployed_{}_stentEX{}_norender.vtp".format(
            dir_path, kind_FD, experiment_number))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Run the FVS deployment simulation and optionally render struts."
    )
    parser.add_argument(
        '--experiment_dir',
        type=str,
        default='./',
        help='Path to the experiment directory containing appSettings.json',
    )
    parser.add_argument(
        '--stent_pos',
        type=str,
        default='inner',
        help="Stent position: 'inner' or 'outer'",
    )
    args = parser.parse_args()
    main(args.experiment_dir, args.stent_pos)
